spring:
  application:
    name: skeleton
server:
  port: 8089

pocket:
  datasource:
    serverId: 101
    node:
      - url: jdbc:mysql://localhost:3306/home?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        nodeName: mysql-01
        driverName: com.mysql.cj.jdbc.Driver
        showSql: true
        user: root
        password: root
        poolMiniSize: 10
        poolMaxSize: 100
        timeout: 1000
        cacheSize: 1000
        session: skeleton,demo
skeleton:
  cache:
    hostName: 127.0.0.1
  token:
    secret: skeleton-secret
    expiration: 1000
    tokenHead: Bearer
  filter:
    excludeUrlPatterns: /login,/register
