pocket:
  datasource:
    node:
      - url: jdbc:oracle:thin:@172.0.66.82:1521:exch
        nodeName: oracle-01
        driverName: oracle.jdbc.driver.OracleDriver
        showSql: true
        collectLog: true
        user: EXCH
        password: EXCH
        poolMiniSize: 5
        poolMaxSize: 50
        timeout: 1
        session: homo,user
      - url: jdbc:oracle:thin:@172.0.66.82:1521:exch
        nodeName: oracle-02
        driverName: oracle.jdbc.driver.OracleDriver
        showSql: true
        collectLog: true
        user: EXCH
        password: EXCH
        poolMiniSize: 5
        poolMaxSize: 50
        timeout: 1
        session: order,commodity

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    org.hv: debug
