server:
  port: 9081
spring:
  application:
    name: bis1039
biscuits:
  serverId: "1039"
  stationId: "00501"
pocket:
  datasource:
    node:
      - url: jdbc:mysql://127.0.0.1:3306/homo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        nodeName: mysql-01
        driverName: com.mysql.cj.jdbc.Driver
        showSql: true
        collectLog: true
        warningLogTimeout: 1000
        encryptedUser: PPBlj83b1dJ+5Z6+4XoE0w==
        encryptedPassword: kV0+tnZsZqNtcrNZTpWECA==
        poolMiniSize: 10
        poolMaxSize: 60
        timeout: 5
        retry: 5
        cacheSize: 1000
        session: homo,user,test
      - url: jdbc:mysql://127.0.0.1:3306/homo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        nodeName: mysql-01-02
        driverName: com.mysql.cj.jdbc.Driver
        showSql: true
        collectLog: true
        warningLogTimeout: 1000
        encryptedUser: PPBlj83b1dJ+5Z6+4XoE0w==
        encryptedPassword: kV0+tnZsZqNtcrNZTpWECA==
        poolMiniSize: 10
        poolMaxSize: 60
        timeout: 5
        retry: 5
        cacheSize: 1000
        session: order,commodity

logging:
  level:
    org.hv: debug
