spring:
  application:
    name: skeleton
server:
  port: 8088

pocket:
  datasource:
    node:
      - url: jdbc:mysql://127.0.0.1:3306/homo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        nodeName: mysql-01
        driverName: com.mysql.cj.jdbc.Driver
        showSql: false
        user: root
        password: root
        poolMiniSize: 10
        poolMaxSize: 15
        timeout: 1000
        session: skeleton
  cache:
    logic:
      hostName: 127.0.0.1
    base:
      hostName: 127.0.0.1
